1:
  title: "Хаски Хелп (Истра)"
  link: "https://walkthedog.ru/huskyhelp"
  donate_link: "https://www.tinkoff.ru/sl/1msxKU5XTyS"
2:
  title: "Приют \"Ника\" (Зеленоград)"
  link: https://walkthedog.ru/nika
  donate_link: "https://www.tinkoff.ru/sl/A3izVb5Cyzn"
3:
  title: "Приют \"Шанс\" (Save Husky, Щелково)"
  link: "https://walkthedog.ru/savehusky"
  donate_link: "https://www.tinkoff.ru/cf/5OrkCaUBo5D"
4:
  title: "Приют \"Домашний\" (Балашиха)"
  link: "https://walkthedog.ru/domashniy_balashikha"
  donate_link: ""
5:
  title: "Биозона (Воскресенск)"
  link: "https://walkthedog.ru/biozona"
  donate_link: "https://www.tinkoff.ru/sl/AG2GLNF5aun"
6:
  title: "Приют \"Домашний\" (Аннино)"
  link: "https://walkthedog.ru/domashniy_annino"
  donate_link: ""
7:
  title: "Центр \"Мокрый нос\" (Зеленоград)"
  link: "https://walkthedog.ru/wetnose"
  donate_link: "https://www.tinkoff.ru/sl/A3izVb5Cyzn"
8:
  title: "Зоотель \"Лемур\" (Воскресенск)"
  link: "https://walkthedog.ru/lemur"
  donate_link: "https://www.tinkoff.ru/sl/24qy6x8P4MP"
