1:
  id: 1
  title: "Хаски Хелп (Истра)"
  address: "Московская область, городской округ Истра, деревня Карцево"
  link: "https://walkthedog.ru/huskyhelp"
  donate_link: "https://www.tinkoff.ru/sl/1msxKU5XTyS"
  schedule:
    type: "regularly"
    details: [1, 6]
    time_start: "11:00"
    time_end: "13:00"
2:
  id: 2
  title: "Приют \"Ника\" (Зеленоград)"
  address: ""
  link: https://walkthedog.ru/nika
  donate_link: "https://www.tinkoff.ru/sl/A3izVb5Cyzn"
  schedule:
    type: "regularly"
    details: [2, 6]
    time_start: "11:00"
    time_end: "13:00"
3:
  id: 3
  title: "Приют \"Шанс\" (Save Husky, Щелково)"
  address: ""
  link: "https://walkthedog.ru/savehusky"
  donate_link: "https://www.tinkoff.ru/cf/5OrkCaUBo5D"
  schedule:
    type: "regularly"
    details: [2, 7]
    time_start: "11:00"
    time_end: "13:00"
4:
  id: 4
  title: "Приют \"Домашний\" (Балашиха)"
  address: ""
  link: "https://walkthedog.ru/domashniy_balashikha"
  donate_link: "https://www.tinkoff.ru/cf/72pWBoJ9qYL"
  schedule:
    type: "regularly"
    details: [3, 6]
    time_start: "11:00"
    time_end: "13:00"
5:
  id: 5
  title: "Биозона (Воскресенск)"
  address: ""
  link: "https://walkthedog.ru/biozona"
  donate_link: "https://www.tinkoff.ru/sl/AG2GLNF5aun"
  schedule:
    type: "regularly"
    details: [3, 6]
    time_start: "11:00"
    time_end: "13:00"
6:
  id: 6
  title: "Приют \"Домашний\" (Аннино)"
  address: ""
  link: "https://walkthedog.ru/domashniy_annino"
  donate_link: "https://www.tinkoff.ru/cf/72pWBoJ9qYL"
  schedule:
    type: "regularly"
    details: [4, 6]
    time_start: "11:00"
    time_end: "13:00"
7:
  id: 7
  title: "Центр \"Мокрый нос\" (Зеленоград)"
  address: ""
  link: "https://walkthedog.ru/wetnose"
  donate_link: "https://www.tinkoff.ru/sl/A3izVb5Cyzn"
  schedule:
    type: "regularly"
    details: [4, 7]
    time_start: "11:00"
    time_end: "13:00"
8:
  id: 8
  title: "Зоотель \"Лемур\" (Воскресенск)"
  address: ""
  link: "https://walkthedog.ru/lemur"
  donate_link: "https://www.tinkoff.ru/sl/24qy6x8P4MP"
  schedule:
    type: "everyday"
    details: []
    time_start: "10:00"
    time_end: "19:00"
