1:
  title: "Хаски Хелп (Истра)"
  link: "https://walkthedog.ru/huskyhelp"
  donate: "https://www.tinkoff.ru/sl/1msxKU5XTyS"
2:
  title: "Приют \"Ника\" (Зеленоград)"
  link: https://walkthedog.ru/nika
  donate: ""
3:
  title: "Приют \"Шанс\" (Save Husky, Щелково)"
  link: "https://walkthedog.ru/savehusky"
  donate: ""
4:
  title: "Приют \"Домашний\" (Балашиха)"
  link: "https://walkthedog.ru/domashniy_balashikha"
  donate: ""
5:
  title: "Биозона (Воскресенск)"
  link: "https://walkthedog.ru/biozona"
  donate: ""
6:
  title: "Приют \"Домашний\" (Аннино)"
  link: "https://walkthedog.ru/domashniy_annino"
  donate: ""
7:
  title: "Центр \"Мокрый нос\" (Зеленоград)"
  link: "https://walkthedog.ru/wetnose"
  donate: ""
8:
  title: "Зоотель \"Лемур\" (Воскресенск)"
  link: "https://walkthedog.ru/lemur"
  donate: ""
  